version: '3.8'
services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/data/postgres

  frontend:
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PATH=/app/node_modules/.bin:$PATH

volumes:
  pg-data:

