version: '3.8'
services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/data/postgres
    networks:
      - backend

  api:
    restart: always
    build:
      context: ./api
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    restart: always
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PATH=/app/node_modules/.bin:$PATH
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    depends_on:
      - api
    networks:
      - frontend

  traefik:
    restart: always
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - frontend

volumes:
  pg-data:

networks:
  backend:
    internal: false #ToDo: change to true later
  frontend:
    internal: false

