version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 20
    networks: 
      - backend

  service1:
    image: myservice
    build:
      context: ./service
    container_name: service1
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - 80
    depends_on:
      postgres:
        condition: service_healthy
    networks: 
      - backend

  service2:
    image: myservice
    container_name: service2
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - 80
    depends_on:
      postgres:
        condition: service_healthy
    networks: 
      - backend

  mygration:
    image: myservice
    command: python manage.py migrate
    depends_on:
      - postgres
      - service1
      - service2
    networks: 
      - backend

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PATH=/app/node_modules/.bin:$PATH
    networks: 
      - frontend

  traefik:
    image: traefik:v2.4
    container_name: traefik
    ports:
      - 80:80
    volumes:
      - "./traefik.toml:/traefik.toml"
      - "./traefik_dynamic.toml:/traefik_dynamic.toml"
    depends_on:
      - service1
      - service2
      - frontend
    networks: 
      - backend
      - frontend

volumes:
  pg_data:

networks:
  backend:
    internal: true #ToDo: change to true later
  frontend:
    internal: false

