[http.routers.dashboard]
rule = "PathPrefix(`/api2`) || PathPrefix(`/dashboard`)"
entrypoints = ["web"]
service = "api@internal"
#middlewares = ["auth"]


[http.routers.myservice]
rule = "PathPrefix(`/`)"
entrypoints = ["web"]
service = "myservice"

[http.services.myservice.loadBalancer.healthCheck]
interval = "3s"
timeout = "1s"

#[http.services.myservice.loadBalancer.sticky.cookie]

[[http.services.myservice.loadBalancer.servers]]
url = "http://service1"
[[http.services.myservice.loadBalancer.servers]]
url = "http://service2"