# Generated by Django 3.1.7 on 2021-04-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyCenter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('amountArchers', models.IntegerField(default=0)),
                ('archerLevel', models.IntegerField(default=0)),
                ('amountBlockers', models.IntegerField(default=0)),
                ('blockerLevel', models.IntegerField(default=0)),
                ('amountSwordsman', models.IntegerField(default=0)),
                ('swordsmanLevel', models.IntegerField(default=0)),
                ('buildinglevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('amountCoal', models.IntegerField(default=0)),
                ('amountIronOre', models.IntegerField(default=0)),
                ('amountDedicatedWorkers', models.IntegerField(default=0)),
                ('buildinglevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Townhall',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('amountWorkersOwned', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('buildinglevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Woodcutters',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('amountWood', models.IntegerField(default=0)),
                ('amountDedicatedWorkers', models.IntegerField(default=0)),
                ('buildinglevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('armyCenter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.armycenter')),
                ('mine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.mine')),
                ('townhall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.townhall')),
                ('woodcutters', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.woodcutters')),
            ],
        ),
    ]
