# Generated by Django 3.1.7 on 2021-04-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyCenter',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('amountArchersLevel1', models.IntegerField(default=0)),
                ('amountArchersLevel2', models.IntegerField(default=0)),
                ('amountArchersLevel3', models.IntegerField(default=0)),
                ('archerLevel', models.IntegerField(default=0)),
                ('amountBlockersLevel1', models.IntegerField(default=0)),
                ('amountBlockersLevel2', models.IntegerField(default=0)),
                ('amountBlockersLevel3', models.IntegerField(default=0)),
                ('blockerLevel', models.IntegerField(default=0)),
                ('amountSwordsmanLevel1', models.IntegerField(default=0)),
                ('amountSwordsmanLevel2', models.IntegerField(default=0)),
                ('amountSwordsmanLevel3', models.IntegerField(default=0)),
                ('swordsmanLevel', models.IntegerField(default=0)),
                ('buildinglevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('amountCoal', models.IntegerField(default=0)),
                ('amountIronOre', models.IntegerField(default=0)),
                ('amountDedicatedWorkers', models.IntegerField(default=0)),
                ('buildinglevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Townhall',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('amountWorkersOwned', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('buildinglevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Woodcutters',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('amountWood', models.IntegerField(default=0)),
                ('amountDedicatedWorkers', models.IntegerField(default=0)),
                ('buildinglevel', models.IntegerField(default=0)),
            ],
        ),
    ]
