# Generated by Django 3.1.7 on 2021-05-05 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armycenter',
            name='archerLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='armycenter',
            name='blockerLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='armycenter',
            name='buildinglevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='armycenter',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 22, 2, 15, 156893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='armycenter',
            name='swordsmanLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mine',
            name='buildinglevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mine',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 22, 2, 15, 155896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='townhall',
            name='amountWorkersOwned',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='townhall',
            name='buildinglevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='townhall',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 22, 2, 15, 156893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='townhall',
            name='money',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='woodcutters',
            name='buildinglevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='woodcutters',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 22, 2, 15, 154898, tzinfo=utc)),
        ),
    ]
