# Generated by Django 3.1.7 on 2021-05-12 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210512_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armycenter',
            name='archerLevel',
        ),
        migrations.RemoveField(
            model_name='armycenter',
            name='blockerLevel',
        ),
        migrations.RemoveField(
            model_name='armycenter',
            name='lastUpdate',
        ),
        migrations.RemoveField(
            model_name='armycenter',
            name='swordsmanLevel',
        ),
        migrations.AlterField(
            model_name='mine',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 19, 49, 1, 456067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='townhall',
            name='money',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='woodcutters',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 19, 49, 1, 455066, tzinfo=utc)),
        ),
    ]
